# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget opencv_core opencv_flann opencv_imgproc opencv_ml opencv_photo opencv_dnn opencv_features2d opencv_imgcodecs opencv_videoio opencv_calib3d opencv_highgui opencv_objdetect opencv_stitching opencv_video opencv_gapi)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target opencv_core
add_library(opencv_core SHARED IMPORTED)

set_target_properties(opencv_core PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
)

# Create imported target opencv_flann
add_library(opencv_flann SHARED IMPORTED)

set_target_properties(opencv_flann PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_core"
)

# Create imported target opencv_imgproc
add_library(opencv_imgproc SHARED IMPORTED)

set_target_properties(opencv_imgproc PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_core"
)

# Create imported target opencv_ml
add_library(opencv_ml SHARED IMPORTED)

set_target_properties(opencv_ml PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_core"
)

# Create imported target opencv_photo
add_library(opencv_photo SHARED IMPORTED)

set_target_properties(opencv_photo PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc;opencv_core;opencv_imgproc"
)

# Create imported target opencv_dnn
add_library(opencv_dnn SHARED IMPORTED)

set_target_properties(opencv_dnn PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc;opencv_core;opencv_imgproc"
)

# Create imported target opencv_features2d
add_library(opencv_features2d SHARED IMPORTED)

set_target_properties(opencv_features2d PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_core;opencv_flann;opencv_imgproc"
)

# Create imported target opencv_imgcodecs
add_library(opencv_imgcodecs SHARED IMPORTED)

set_target_properties(opencv_imgcodecs PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc;opencv_core;opencv_imgproc"
)

# Create imported target opencv_videoio
add_library(opencv_videoio SHARED IMPORTED)

set_target_properties(opencv_videoio PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_core;opencv_imgproc;opencv_imgcodecs"
)

# Create imported target opencv_calib3d
add_library(opencv_calib3d SHARED IMPORTED)

set_target_properties(opencv_calib3d PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d"
)

# Create imported target opencv_highgui
add_library(opencv_highgui SHARED IMPORTED)

set_target_properties(opencv_highgui PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio"
)

# Create imported target opencv_objdetect
add_library(opencv_objdetect SHARED IMPORTED)

set_target_properties(opencv_objdetect PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_stitching
add_library(opencv_stitching SHARED IMPORTED)

set_target_properties(opencv_stitching PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d;opencv_core;opencv_flann;opencv_imgproc;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_video
add_library(opencv_video SHARED IMPORTED)

set_target_properties(opencv_video PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_dnn;opencv_features2d;opencv_calib3d;opencv_core;opencv_flann;opencv_imgproc;opencv_dnn;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_gapi
add_library(opencv_gapi SHARED IMPORTED)

set_target_properties(opencv_gapi PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/core/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/flann/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgproc/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ml/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/photo/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/dnn/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/features2d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/imgcodecs/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/videoio/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/calib3d/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/highgui/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/objdetect/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/stitching/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/ts/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/video/include;C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/extern/opencv/modules/gapi/include"
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_dnn;opencv_features2d;opencv_calib3d;opencv_video;opencv_core;opencv_flann;opencv_imgproc;opencv_dnn;opencv_features2d;opencv_calib3d;opencv_video"
)

# Import target "opencv_core" for configuration "Debug"
set_property(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_core PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_core453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_core453d.dll"
  )

# Import target "opencv_flann" for configuration "Debug"
set_property(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_flann PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_flann453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_flann453d.dll"
  )

# Import target "opencv_imgproc" for configuration "Debug"
set_property(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_imgproc PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_imgproc453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_imgproc453d.dll"
  )

# Import target "opencv_ml" for configuration "Debug"
set_property(TARGET opencv_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_ml PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_ml453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_ml453d.dll"
  )

# Import target "opencv_photo" for configuration "Debug"
set_property(TARGET opencv_photo APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_photo PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_photo453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_photo453d.dll"
  )

# Import target "opencv_dnn" for configuration "Debug"
set_property(TARGET opencv_dnn APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_dnn PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_dnn453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_dnn453d.dll"
  )

# Import target "opencv_features2d" for configuration "Debug"
set_property(TARGET opencv_features2d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_features2d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_features2d453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_features2d453d.dll"
  )

# Import target "opencv_imgcodecs" for configuration "Debug"
set_property(TARGET opencv_imgcodecs APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_imgcodecs PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_imgcodecs453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_imgcodecs453d.dll"
  )

# Import target "opencv_videoio" for configuration "Debug"
set_property(TARGET opencv_videoio APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_videoio PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_videoio453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_videoio453d.dll"
  )

# Import target "opencv_calib3d" for configuration "Debug"
set_property(TARGET opencv_calib3d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_calib3d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_calib3d453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_calib3d453d.dll"
  )

# Import target "opencv_highgui" for configuration "Debug"
set_property(TARGET opencv_highgui APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_highgui PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_highgui453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_highgui453d.dll"
  )

# Import target "opencv_objdetect" for configuration "Debug"
set_property(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_objdetect PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_objdetect453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_objdetect453d.dll"
  )

# Import target "opencv_stitching" for configuration "Debug"
set_property(TARGET opencv_stitching APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_stitching PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_stitching453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_stitching453d.dll"
  )

# Import target "opencv_video" for configuration "Debug"
set_property(TARGET opencv_video APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_video PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_video453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_video453d.dll"
  )

# Import target "opencv_gapi" for configuration "Debug"
set_property(TARGET opencv_gapi APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_gapi PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Debug/opencv_gapi453d.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Debug/opencv_gapi453d.dll"
  )

# Import target "opencv_core" for configuration "Release"
set_property(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_core PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_core453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_core453.dll"
  )

# Import target "opencv_flann" for configuration "Release"
set_property(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_flann PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_flann453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_flann453.dll"
  )

# Import target "opencv_imgproc" for configuration "Release"
set_property(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_imgproc PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_imgproc453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_imgproc453.dll"
  )

# Import target "opencv_ml" for configuration "Release"
set_property(TARGET opencv_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ml PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_ml453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_ml453.dll"
  )

# Import target "opencv_photo" for configuration "Release"
set_property(TARGET opencv_photo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_photo PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_photo453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_photo453.dll"
  )

# Import target "opencv_dnn" for configuration "Release"
set_property(TARGET opencv_dnn APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_dnn PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_dnn453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_dnn453.dll"
  )

# Import target "opencv_features2d" for configuration "Release"
set_property(TARGET opencv_features2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_features2d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_features2d453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_features2d453.dll"
  )

# Import target "opencv_imgcodecs" for configuration "Release"
set_property(TARGET opencv_imgcodecs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_imgcodecs PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_imgcodecs453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_imgcodecs453.dll"
  )

# Import target "opencv_videoio" for configuration "Release"
set_property(TARGET opencv_videoio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_videoio PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_videoio453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_videoio453.dll"
  )

# Import target "opencv_calib3d" for configuration "Release"
set_property(TARGET opencv_calib3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_calib3d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_calib3d453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_calib3d453.dll"
  )

# Import target "opencv_highgui" for configuration "Release"
set_property(TARGET opencv_highgui APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_highgui PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_highgui453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_highgui453.dll"
  )

# Import target "opencv_objdetect" for configuration "Release"
set_property(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_objdetect PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_objdetect453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_objdetect453.dll"
  )

# Import target "opencv_stitching" for configuration "Release"
set_property(TARGET opencv_stitching APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_stitching PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_stitching453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_stitching453.dll"
  )

# Import target "opencv_video" for configuration "Release"
set_property(TARGET opencv_video APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_video PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_video453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_video453.dll"
  )

# Import target "opencv_gapi" for configuration "Release"
set_property(TARGET opencv_gapi APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_gapi PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/Release/opencv_gapi453.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/Release/opencv_gapi453.dll"
  )

# Import target "opencv_core" for configuration "MinSizeRel"
set_property(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_core PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_core453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_core453.dll"
  )

# Import target "opencv_flann" for configuration "MinSizeRel"
set_property(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_flann PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_flann453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_flann453.dll"
  )

# Import target "opencv_imgproc" for configuration "MinSizeRel"
set_property(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_imgproc PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_imgproc453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_imgproc453.dll"
  )

# Import target "opencv_ml" for configuration "MinSizeRel"
set_property(TARGET opencv_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_ml PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_ml453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_ml453.dll"
  )

# Import target "opencv_photo" for configuration "MinSizeRel"
set_property(TARGET opencv_photo APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_photo PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_photo453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_photo453.dll"
  )

# Import target "opencv_dnn" for configuration "MinSizeRel"
set_property(TARGET opencv_dnn APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_dnn PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_dnn453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_dnn453.dll"
  )

# Import target "opencv_features2d" for configuration "MinSizeRel"
set_property(TARGET opencv_features2d APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_features2d PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_features2d453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_features2d453.dll"
  )

# Import target "opencv_imgcodecs" for configuration "MinSizeRel"
set_property(TARGET opencv_imgcodecs APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_imgcodecs PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_imgcodecs453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_imgcodecs453.dll"
  )

# Import target "opencv_videoio" for configuration "MinSizeRel"
set_property(TARGET opencv_videoio APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_videoio PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_videoio453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_videoio453.dll"
  )

# Import target "opencv_calib3d" for configuration "MinSizeRel"
set_property(TARGET opencv_calib3d APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_calib3d PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_calib3d453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_calib3d453.dll"
  )

# Import target "opencv_highgui" for configuration "MinSizeRel"
set_property(TARGET opencv_highgui APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_highgui PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_highgui453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_highgui453.dll"
  )

# Import target "opencv_objdetect" for configuration "MinSizeRel"
set_property(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_objdetect PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_objdetect453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_objdetect453.dll"
  )

# Import target "opencv_stitching" for configuration "MinSizeRel"
set_property(TARGET opencv_stitching APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_stitching PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_stitching453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_stitching453.dll"
  )

# Import target "opencv_video" for configuration "MinSizeRel"
set_property(TARGET opencv_video APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_video PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_video453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_video453.dll"
  )

# Import target "opencv_gapi" for configuration "MinSizeRel"
set_property(TARGET opencv_gapi APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(opencv_gapi PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/MinSizeRel/opencv_gapi453.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/MinSizeRel/opencv_gapi453.dll"
  )

# Import target "opencv_core" for configuration "RelWithDebInfo"
set_property(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_core PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_core453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_core453.dll"
  )

# Import target "opencv_flann" for configuration "RelWithDebInfo"
set_property(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_flann PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_flann453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_flann453.dll"
  )

# Import target "opencv_imgproc" for configuration "RelWithDebInfo"
set_property(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_imgproc PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_imgproc453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_imgproc453.dll"
  )

# Import target "opencv_ml" for configuration "RelWithDebInfo"
set_property(TARGET opencv_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_ml PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_ml453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_ml453.dll"
  )

# Import target "opencv_photo" for configuration "RelWithDebInfo"
set_property(TARGET opencv_photo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_photo PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_photo453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_photo453.dll"
  )

# Import target "opencv_dnn" for configuration "RelWithDebInfo"
set_property(TARGET opencv_dnn APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_dnn PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_dnn453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_dnn453.dll"
  )

# Import target "opencv_features2d" for configuration "RelWithDebInfo"
set_property(TARGET opencv_features2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_features2d PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_features2d453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_features2d453.dll"
  )

# Import target "opencv_imgcodecs" for configuration "RelWithDebInfo"
set_property(TARGET opencv_imgcodecs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_imgcodecs PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_imgcodecs453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_imgcodecs453.dll"
  )

# Import target "opencv_videoio" for configuration "RelWithDebInfo"
set_property(TARGET opencv_videoio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_videoio PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_videoio453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_videoio453.dll"
  )

# Import target "opencv_calib3d" for configuration "RelWithDebInfo"
set_property(TARGET opencv_calib3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_calib3d PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_calib3d453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_calib3d453.dll"
  )

# Import target "opencv_highgui" for configuration "RelWithDebInfo"
set_property(TARGET opencv_highgui APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_highgui PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_highgui453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_highgui453.dll"
  )

# Import target "opencv_objdetect" for configuration "RelWithDebInfo"
set_property(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_objdetect PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_objdetect453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_objdetect453.dll"
  )

# Import target "opencv_stitching" for configuration "RelWithDebInfo"
set_property(TARGET opencv_stitching APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_stitching PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_stitching453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_stitching453.dll"
  )

# Import target "opencv_video" for configuration "RelWithDebInfo"
set_property(TARGET opencv_video APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_video PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_video453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_video453.dll"
  )

# Import target "opencv_gapi" for configuration "RelWithDebInfo"
set_property(TARGET opencv_gapi APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(opencv_gapi PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/extern/opencv/lib/RelWithDebInfo/opencv_gapi453.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/21166/Desktop/Work/CodeProjects/GLCSVS/build/bin/RelWithDebInfo/opencv_gapi453.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
